### ISSUE TITLE
Expired SSL certificate of https://ocharles.org.uk

### ISSUE THREAD

**Issue by vcunat** [ocharles/blog#24]

**Comment by vcunat** [comment]
I seem to be lucky, as it's supposed to have expired just today.

**Comment by ocharles** [comment]
Yea, I'm working on it. I bought the certificate a while ago, but haven't got round to configuring... and it's a big NixOS rebuild to deploy :D Should be fixed tonight.

**Comment by vcunat** [comment]
:-D Yes, sometimes I lose some information and reconfigurations need to rebuild lots of things.

**Comment by vcunat** [comment]
Seems fixed now.

**Comment by ocharles** [comment]
You'd hope so, after 13 days ;)
