### ISSUE TITLE
SDL2 blog post code doesn't compile

### ISSUE THREAD

**Issue by FranklinChen** [ocharles/blog#28]
I copied and pasted the code at https://ocharles.org.uk/blog/posts/2015-09-07-announcing-sdl2.html and it doesn't compile with sdl2-2.0.0.

**Comment by ocharles** [comment]
Thanks, I made some last minute API changes after writing the post that causes it to fail to compile. https://github.com/haskell-game/sdl2/pull/77 is tracking that documentation bug, too - so hopefully we'll have correct code soon! In the meantime, perhaps check out the [examples](https://github.com/haskell-game/sdl2/tree/master/examples). And thanks for the diligence when it comes to reporting my sloppy blog post authoring!

**Comment by ocharles** [comment]
Ok, blog post updated.
