### ISSUE TITLE
No repo for fast-downward?

### ISSUE THREAD

**Issue by alexfmpe** [ocharles/blog#43]
I couldn’t find a repo mentioned in the blog post (nor indirectly via the linked hackage package)

**Comment by ocharles** [comment]
A good observation! This work actually came out if a folder in private CircuitHub work, but obviously the open source release warrants a proper repo. I'll set something up now.

**Comment by ocharles** [comment]
Ok, it's at https://github.com/circuithub/fast-downward and I updated the Cabal metadata.
